kind: pipeline
name: default

volumes:
- name: docker-config
  host:
    path:  /root/.docker/config.json

steps:
- name: docker
  image: registry.lqm.io/dind
  privileged: true
  detach: true

- name: publish artifact
  image: registry.lqm.io/dind
  volumes:
  - name: docker-config
    path: /root/.docker/config.json
  environment:
    DOCKER_HOST: docker:2375
    GSUTIL_CONFIG_JSON:
      from_secret: GSUTIL_CONFIG_JSON
  commands:
  - gsutil-login.sh
  - make publish-artifact
  - make publish-image
