kind: pipeline
name: default

image_pull_secrets:
  - DOCKER_CONFIG_JSON

steps:
- name: docker
  image: registry.lqm.io/dind
  privileged: true
  detach: true

- name: publish artifact
  image: registry.lqm.io/dind
  environment:
    DOCKER_HOST: docker:2375
    GSUTIL_CONFIG_JSON:
      from_secret: GSUTIL_CONFIG_JSON
  commands:
  - gsutil-login.sh
  - make publish-artifact
  - make publish-image
